import Head from "next/head";
import { useSelector } from "react-redux";
import AdminLogin from "../../../components/AdminDashboard/AdminLogin";
import ViewEnrolledStudent from "../../../components/AdminDashboard/Enrollments/ViewEnrolledStudents/ViewEnrolledStudents";
import AdminLayout from "../../../components/Utils/AdminLayout/AdminLayout";

export default function ProfileDetailPage(props) {
  
  const auth = useSelector((state) => state.adminSlice.authInfo);
  if (!auth.isAuthenticated) {
    return <AdminLogin />;
  }

  return (
    <AdminLayout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ViewEnrolledStudent students={props.students} />
    </AdminLayout>
  );
}

export async function getStaticPaths() {
  const res = await fetch(
    "https://saraswati-45e10-default-rtdb.firebaseio.com/OnlineClass/Enrollments.json"
  );
  const data = await res.json();

  let courseIds = [];
  for (const key in data) {
    courseIds.push(key);
  }

  const paths = courseIds.map((item) => {
    return {
      params: { courseId: item },
    };
  });

  return {
    paths: paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const courseId = context.params.courseId;

  const courseRes = await fetch(
    `https://saraswati-45e10-default-rtdb.firebaseio.com/OnlineClass/Enrollments/${courseId}.json`
  );
  const data = await courseRes.json();

  let enrolledStudents = [];
  for (const key in data) {
    const student = data[key];
    enrolledStudents.push(student);
  }

  return {
    props: {
      students: enrolledStudents,
    },
  };
}

/*export async function getStaticProps(context) {
  const teacherId = context.params.teacherId;

  const tutorRes = await fetch(
    `https://saraswati-45e10-default-rtdb.firebaseio.com/teachers/profiles/${teacherId}.json`
  );
  const tutorInfo = await tutorRes.json();

  const coursesRes = await fetch(`https://saraswati-45e10-default-rtdb.firebaseio.com/teachers/courses/${teacherId}.json`);
  const coursesInfo = await coursesRes.json();

  let courses = [];
  for (const key in coursesInfo) {
    const course = coursesInfo[key];
    courses.push(course);
  }

  return {
    props: {
      tutorInfo : tutorInfo,
      courses : courses
    },
  };
}*/
