import Head from "next/head";
import MyEnrollments from "../../../components/StudentDashboard/MyEnrollments/MyEnrollments";
import StudentLayout from '../../../components/Utils/StudentLayout/StudentLayout';

export default function MyEnrollmentsPage(props) {
  return (
    <StudentLayout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyEnrollments />
    </StudentLayout>
  );
}