import Head from "next/head";
import { useSelector } from "react-redux";
import Login from "../../../components/Users/Authenticate/Login/Login";
import MyEnrollments from "../../../components/StudentDashboard/MyEnrollments/MyEnrollments";
import StudentLayout from '../../../components/Utils/StudentLayout/StudentLayout';

export default function MyEnrollmentsPage(props) {

  const auth = useSelector((state) => state.userSlice.authInfo);
  if(!auth.isAuthenticated){
    return <Login />
  }

  return (
    <StudentLayout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyEnrollments />
    </StudentLayout>
  );
}