import Head from "next/head";
import StudentDashboard from "../../components/StudentDashboard/StudentDashboard";
import StudentLayout from '../../components/Utils/StudentLayout/StudentLayout';

export default function HomePage(props) {
  return (
    <StudentLayout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StudentDashboard />
    </StudentLayout>
  );
}