import Head from "next/head";
import HomeTutors from "../../components/Users/HomeTutors/HomeTutors";
import Layout from "../../components/Utils/Layout/Layout";

export default function HomePage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTutors />
    </Layout>
  );
}