import Head from "next/head";
import ClassroomCourses from "../../components/Users/ClassroomCourses/ClassroomCourses";
import Layout from "../../components/Utils/Layout/Layout";

export default function ClassrommCoursesPage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClassroomCourses />
    </Layout>
  );
}