import Head from "next/head";
import Layout from "../../../components/Utils/Layout/Layout";
import PaymentStatus from "../../../components/Users/PaymentStatus/PaymentStatus";

export default function PaymentStatusPage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaymentStatus query={props} />
    </Layout>
  );
}

PaymentStatusPage.getInitialProps = ({ query }) => {
  /*const pairs = query.payment_status.split("&");
  const payment_id_data = pairs[0].split("=");
  const payment_status_data = pairs[1].split("=");
  const payment_request_id_data = pairs[2].split("=");

  return {
    payment_id: payment_id_data[1],
    payment_status: payment_status_data[1],
    payment_request_id: payment_request_id_data[1],
  };*/
  return {
    query: query
  }
};
