import Head from "next/head";
import Enrollment from "../../../components/Users/OnlineClass/Enrollment/Enrollment";
import Layout from "../../../components/Utils/Layout/Layout";

const courses = [
  {
    courseId: "id1",
    title: "Engineering Physics",
    tutor: "B Nath",
    description: "Complete Engineering Physics Course",
  },
  {
      courseId: "id2",
      title: "Engineering Chemistry",
      tutor: "B Nath",
      description: "Complete Engineering Chemistry Course",
    }
];

export default function HomePage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Enrollment data={props.data} />
    </Layout>
  );
}

export const getStaticPaths = async () => {
  return {
    paths: [
      {
        params: { courseId: "id1" },
      },
      {
        params: { courseId: "id2" },
      },
    ],
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const courseId = context.params.courseId;

  const item = courses.find(item => item.courseId === courseId);

  return {
    props: {
      data: item
    },
  };
};
