import Head from "next/head";
import Enrollment from "../../../components/Users/OnlineClass/Enrollment/Enrollment";
import Layout from "../../../components/Utils/Layout/Layout";

export default function HomePage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Enrollment data={props.data} />
    </Layout>
  );
}

export async function getStaticPaths() {
  const res = await fetch(
    "https://saraswati-45e10-default-rtdb.firebaseio.com/OnlineClass/Courses.json"
  );
  const data = await res.json();

  let courses = [];
  for (const key in data) {
    const course = data[key];
    courses.push(course);
  }

  const paths = courses.map((item) => {
    return {
      params: { courseId: item.courseId },
    };
  });

  return {
    paths: paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const courseId = context.params.courseId;

  const courseRes = await fetch(
    `https://saraswati-45e10-default-rtdb.firebaseio.com/OnlineClass/Courses/${courseId}.json`
  );
  const item = await courseRes.json();

  return {
    props: {
      data : item
    },
    revalidate : 10,
  };
}

/*
export const getStaticPaths = async () => {
  return {
    paths: [
      {
        params: { courseId: "id1" },
      },
      {
        params: { courseId: "id2" },
      },
    ],
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const courseId = context.params.courseId;

  const item = courses.find(item => item.courseId === courseId);

  return {
    props: {
      data: item
    },
  };
}; */
