import Head from "next/head";
import Enrollment from "../../../components/Users/OnlineClass/Enrollment/Enrollment";
import Layout from "../../../components/Utils/Layout/Layout";

export default function HomePage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Enrollment/>
    </Layout>
  );
}