import Head from "next/head";
import Home from "../components/Home/Home";
import styles from "../styles/Home.module.css";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
