import Head from "next/head";
import Login from "../components/Users/Authenticate/Login/Login";
import Layout from "../components/Utils/Layout/Layout";

export default function LoginPage(props) {
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </Layout>
  );
}