import Head from "next/head";
import AdminLayout from "../../../../components/Utils/AdminLayout/AdminLayout";
import AdminLogin from "../../../../components/AdminDashboard/AdminLogin";
import BookingDetail from "../../../../components/AdminDashboard/HomeTutorBookings/BookingDetail/BookingDetail";
import { useSelector } from "react-redux";

export default function BookingDetailPage(props){
    const auth = useSelector(state=> state.adminSlice.authInfo);
    if(!auth.isAuthenticated){
      return <AdminLogin />
    }

    return (
        <AdminLayout>
        <Head>
          <title>Saraswati Tutorials</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <BookingDetail bookingData={props.bookingData} />
      </AdminLayout>
    );
}

export async function getServerSideProps(context){
  const bookingId = context.params.bookingId;

  const res = await fetch(
    `https://saraswati-45e10-default-rtdb.firebaseio.com/HomeTutors/Bookings/${bookingId}.json`
  );
  const data = await res.json();

  return {
    props: {
      bookingData : data,
    }
  };
}