import Head from "next/head";
import BookingSummary from "../../../components/Users/HomeTutor/BookingSummary/BookingSummary";
import Layout from "../../../components/Utils/Layout/Layout";

export default function ProfileDetailPage(props) {
  console.log("data in bookingPage : "+props.info);
  return (
    <Layout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookingSummary />
    </Layout>
  );
}