import Head from "next/head";
import TeacherProfileDetail from "../../../components/Users/HomeTutor/TeacherProfileDetail/TeacherProfileDetail";
import Layout from "../../../components/Utils/Layout/Layout";

export default function ProfileDetailPage(){
    return (
        <Layout>
        <Head>
          <title>Saraswati Tutorials</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <TeacherProfileDetail />
      </Layout>
    );
}