import Head from "next/head";
import { useSelector } from "react-redux";
import HomeTutorLogin from "../../components/HomeTutorDashboard/HomeTutorAuthenticate/HomeTutorLogin/HomeTutorLogin";
import HomeTutorDashboard from "../../components/HomeTutorDashboard/HomeTutorDashboard";
import HomeTutorLayout from "../../components/Utils/HomeTutorLayout/HomeTutorLayout";

export default function HomePage(props) {

  const auth = useSelector((state) => state.homeTutorUserSlice.authInfo);
  if(!auth.isAuthenticated){
    return <HomeTutorLogin/>
  }

  return (
    <HomeTutorLayout>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTutorDashboard />
    </HomeTutorLayout>
  );
}