import Head from "next/head";
import HomeTutorSignUp from "../../components/HomeTutorDashboard/HomeTutorAuthenticate/HomeTutorSignup/HomeTutorSignup";
import HomeTutorLayout from "../../components/Utils/HomeTutorLayout/HomeTutorLayout";

export default function HomeTutorSignupPage(props) {

  return (
    <>
      <Head>
        <title>Saraswati Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTutorSignUp />
    </>
  );
}